// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY34kVN2yc6QyGwH8AAI6PoXWN9Zl5JNA',
    appId: '1:332215194121:web:f6084a49320d15a3fd9ed8',
    messagingSenderId: '332215194121',
    projectId: 'chat-app-28ba6',
    authDomain: 'chat-app-28ba6.firebaseapp.com',
    storageBucket: 'chat-app-28ba6.appspot.com',
    measurementId: 'G-Z9D13ZW543',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKENjuuuNBHBRsP4gbYU2H9nKJ6AlJHlY',
    appId: '1:332215194121:android:64df3c8d6b222324fd9ed8',
    messagingSenderId: '332215194121',
    projectId: 'chat-app-28ba6',
    storageBucket: 'chat-app-28ba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd9omkyCw-d-0SK4T0B1vdn9IslB2X7fk',
    appId: '1:332215194121:ios:b26ed93e441a7b60fd9ed8',
    messagingSenderId: '332215194121',
    projectId: 'chat-app-28ba6',
    storageBucket: 'chat-app-28ba6.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd9omkyCw-d-0SK4T0B1vdn9IslB2X7fk',
    appId: '1:332215194121:ios:b26ed93e441a7b60fd9ed8',
    messagingSenderId: '332215194121',
    projectId: 'chat-app-28ba6',
    storageBucket: 'chat-app-28ba6.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY34kVN2yc6QyGwH8AAI6PoXWN9Zl5JNA',
    appId: '1:332215194121:web:a271a480f623ac85fd9ed8',
    messagingSenderId: '332215194121',
    projectId: 'chat-app-28ba6',
    authDomain: 'chat-app-28ba6.firebaseapp.com',
    storageBucket: 'chat-app-28ba6.appspot.com',
    measurementId: 'G-LH0GXKW9TZ',
  );

}